backend:
  name: github
  repo: migueldorosario1/rio-carta
  branch: main

media_folder: "public/hero"
public_folder: "/hero"

collections:
  - name: "blog"
    label: "Matérias (Rio Carta)"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Subtítulo (Description)", name: "description", widget: "string"}
      - {label: "Data de Publicação", name: "pubDate", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Imagem de Capa", name: "heroImage", widget: "image"}
      - {label: "Tags (Categorias ou Bairros)", name: "tags", widget: "list", default: ["rio-de-janeiro"]}
      - {label: "Corpo do Texto", name: "body", widget: "markdown"}
